title: Networks Lab NITC - CSED S6 - Winter (2024-2025)
description: A documentation of activities performed under the Networks Lab Course under CSED, NIT-C for Semester-6 students in the year 2025.
theme: just-the-docs

logo: "/assets/images/icons8-router-symbol-dotted-96.png"
domain: jaefarnc.github.io
url: https://jaefarnc.github.io
baseurl: /nwlab
aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/jaefarnc/nwlab
